# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "qaul"
license = "CC-BY"
licenselink = "https://github.com/qaul/qaul-website/blob/master/LICENSE"
description = ""
homepage = "http://qaul.net/"
tags = []
features = []
min_version = "0.41"

[author]
  name = "qaul Community"
  homepage = "https://qaul.net"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
